

<?php $__env->startSection('title', 'Warehouse Grid'); ?>

<?php $__env->startSection('head'); ?>
    <link rel="stylesheet" href="<?php echo e(asset('css/grid.css')); ?>?v=<?php echo e(time()); ?>">
    <meta name="csrf-token" content="<?php echo e(csrf_token()); ?>">
    <meta name="warehouse-id" content="<?php echo e($warehouse->id); ?>">

    <style>
        /* page content */
        .content {
            flex: 1;
            width: 100%;
            padding: 0px 0px !important;
        }
    </style>
<?php $__env->stopSection(); ?>

<?php $__env->startSection('content'); ?>

    <div class="grid-container">
        <!-- Left Sidebar -->
        <div class="sidebar">
            <div class="sidebar-header">
                <h2 id="warehouseNameDisplay" class="editable-warehouse-name" title="Click to edit">
                    <?php echo e($warehouse->warehouse_name); ?></h2>
                <input type="text" id="warehouseNameInput" class="warehouse-name-input" style="display: none;"
                    value="<?php echo e($warehouse->warehouse_name); ?>">
                <div class="header-buttons">
                    <a href="<?php echo e(route('dashboard')); ?>" class="btn-back">← Back</a>
                    <button type="button" class="btn-share" data-bs-toggle="modal" data-bs-target="#shareWarehouseModal">
                        Share
                    </button>
                </div>
            </div>

            <!-- Search Bar -->
            <div class="search-container">
                <input type="text" id="searchInput" class="search-input" placeholder="Search products...">
                <button id="clearSearchBtn" class="btn-clear-search">×</button>
            </div>

            <!-- Create Section Button -->
            <button type="button" class="btn-create-section" id="createSectionBtn">
                + Create Section
            </button>

            <!-- Sections List -->
            <div class="sections-list" id="sectionsList">
                <?php $__currentLoopData = $warehouse->sections; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $section): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <div class="section-item" data-section-id="<?php echo e($section->id); ?>" data-grid-x="<?php echo e($section->grid_x); ?>"
                        data-grid-y="<?php echo e($section->grid_y); ?>">
                        <div class="section-item-header">
                            <span class="section-item-name editable-section-name" data-section-id="<?php echo e($section->id); ?>"
                                title="Click to edit"><?php echo e($section->section_name); ?></span>
                            <div class="section-item-actions">
                                <button class="btn-add-product" data-section-id="<?php echo e($section->id); ?>">+</button>
                                <button class="btn-delete-section" data-section-id="<?php echo e($section->id); ?>">×</button>
                            </div>
                        </div>
                        <div class="section-item-products">
                            <?php $__currentLoopData = $section->products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $product): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                <div class="product-item-small" data-product-id="<?php echo e($product->id); ?>"
                                    data-section-id="<?php echo e($section->id); ?>">
                                    <span class="product-item-name"><?php echo e($product->product_name); ?></span>
                                    <span class="product-item-qty">Qty: <?php echo e($product->quantity); ?></span>
                                    <button class="btn-edit-product" data-section-id="<?php echo e($section->id); ?>"
                                        data-product-id="<?php echo e($product->id); ?>">✎</button>
                                    <button class="btn-delete-product" data-section-id="<?php echo e($section->id); ?>"
                                        data-product-id="<?php echo e($product->id); ?>">×</button>
                                </div>
                            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                        </div>
                    </div>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </div>
        </div>

        <!-- Main Grid Area -->
        <div class="grid-area">
            <div class="grid-canvas" id="gridCanvas">
                <!-- Grid cells will be generated by JavaScript -->
            </div>
        </div>
    </div>

    <!-- Modal for Creating Section -->
    <div class="modal fade" id="createSectionModal" tabindex="-1" aria-labelledby="createSectionModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createSectionModalLabel">Create New Section</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="text" class="form-control" id="sectionNameInput" placeholder="Enter section name">
                    <p class="modal-hint">Click on an empty grid cell to place the section</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Adding Product -->
    <div class="modal fade" id="createProductModal" tabindex="-1" aria-labelledby="createProductModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="createProductModalLabel">Add Product to <span id="modalSectionName"></span>
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="productSectionId">
                    <div class="mb-3">
                        <label for="productName" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="productName" placeholder="Enter product name">
                    </div>
                    <div class="mb-3">
                        <label for="productSku" class="form-label">SKU (Optional)</label>
                        <input type="text" class="form-control" id="productSku" placeholder="Enter SKU">
                    </div>
                    <div class="mb-3">
                        <label for="productQuantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="productQuantity" placeholder="Enter quantity"
                            value="0" min="0">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="addProductBtn">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Editing Product -->
    <div class="modal fade" id="editProductModal" tabindex="-1" aria-labelledby="editProductModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="editProductModalLabel">Edit Product</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="editProductId">
                    <input type="hidden" id="editProductSectionId">
                    <div class="mb-3">
                        <label for="editProductName" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="editProductName"
                            placeholder="Enter product name">
                    </div>
                    <div class="mb-3">
                        <label for="editProductSku" class="form-label">SKU (Optional)</label>
                        <input type="text" class="form-control" id="editProductSku" placeholder="Enter SKU">
                    </div>
                    <div class="mb-3">
                        <label for="editProductQuantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="editProductQuantity" placeholder="Enter quantity"
                            value="0" min="0">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" id="updateProductBtn">Update Product</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Sharing Warehouse -->
    <div class="modal fade" id="shareWarehouseModal" tabindex="-1" aria-labelledby="shareWarehouseModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="shareWarehouseModalLabel">Share Warehouse</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="shareEmail" class="form-label">User Email</label>
                        <input type="email" class="form-control" id="shareEmail" placeholder="Enter user email">
                    </div>
                    <button type="button" class="btn btn-primary mb-3" id="shareWarehouseBtn">Add User</button>

                    <hr class="my-4">

                    <h6 class="shared-users-title">Users with Access</h6>
                    <div id="sharedUsersList" class="shared-users-list">
                        <!-- Shared users will be loaded here -->
                        <p class="loading-users">Loading...</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

<?php $__env->stopSection(); ?>

<?php $__env->startSection('scripts'); ?>
    <script src="<?php echo e(asset('js/grid.js')); ?>?v=<?php echo e(time()); ?>"></script>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.template', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\louis\vscodeprojects\FinalProject\WhereHouse\resources\views/grid.blade.php ENDPATH**/ ?>